<#
.SYNOPSIS
    在桌面（以及开始菜单）装一个「一键启动 cv-research 宿主」的入口。

.DESCRIPTION
    为什么要有这个脚本，而不是手工丢一个文件到桌面：
    入口文件里写的是**绝对路径**（仓库位置、powershell 路径），换机器/换用户/挪仓库
    都会失效。把生成过程脚本化，就能随时重建，也能在另一台机器上一条命令装好。

    生成物：
      1. 桌面 `启动 CV-Research.cmd` —— 双击即用。行为：
         - 宿主已在跑 → 直接打开浏览器（不重复起宿主）
         - 宿主没跑   → 注入前置（代理 / 密钥 / skill 根）并启动
         - 代理没开   → 提示并等你启动，避免起出一个"没有检索工具"的宿主
      2. 开始菜单 `CV-Research 宿主.lnk` —— 开始菜单搜 "cv" 就能找到（可选，-NoStartMenu 跳过）

    编码注意（踩过的坑，见勘误 E28）：`.cmd` 内容**必须是纯 ASCII**。
    cmd.exe 按 OEM 代码页（中文 Windows 是 936）读 `.cmd`，UTF-8 中文会变乱码；
    而带 BOM 又会让 cmd.exe 把首行 `@echo off` 当命令报错。所以：**cmd 壳纯 ASCII，
    所有中文提示都由 PowerShell（UTF-8 + BOM）输出**。本文件自己含中文，故必须是
    UTF-8 **带 BOM** 的 .ps1（guardrail 测试会检查这一点）。

.PARAMETER RepoRoot
    仓库根。缺省取本脚本所在目录的上一级。

.PARAMETER NoStartMenu
    只装桌面入口，不装开始菜单。

.PARAMETER LauncherPath
    生成的 .cmd 路径。缺省是桌面上的「启动 CV-Research.cmd」。
    这个参数主要为**自动化测试**服务：把生成物写到临时目录再校验编码与内容
    （护栏 `tests/ps1-encoding.test.ts` 就是这样端到端验证的）。

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\install-desktop-shortcut.ps1
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\install-desktop-shortcut.ps1 -NoStartMenu
#>
param(
    [string]$RepoRoot = (Split-Path $PSScriptRoot -Parent),
    [switch]$NoStartMenu,
    [string]$LauncherPath = ''
)

$ErrorActionPreference = 'Stop'

$startScript = Join-Path $RepoRoot 'scripts\start-dsh-web.ps1'
if (-not (Test-Path $startScript)) {
    throw "找不到启动脚本：$startScript（-RepoRoot 是否指对了仓库根？）"
}

$desktop = [Environment]::GetFolderPath('Desktop')
# -LauncherPath 主要为自动化测试服务：把生成物写到临时目录，再校验编码与内容
$launcherPath = if ($LauncherPath -ne '') { $LauncherPath } else { Join-Path $desktop '启动 CV-Research.cmd' }

# ── 1. 桌面 .cmd（纯 ASCII；中文一律交给 PowerShell 输出）──────────────────
# %* 把参数透传，便于 `启动 CV-Research.cmd -DryRun` 这类排查用法。
$launcher = @"
@echo off
rem ===================================================================
rem  cv-research launcher (generated by scripts/install-desktop-shortcut.ps1)
rem  ASCII-only on purpose: cmd.exe decodes .cmd with the OEM codepage,
rem  so non-ASCII here would be mojibake (and a BOM breaks line 1).
rem  All human-facing text is printed by start-dsh-web.ps1 instead.
rem ===================================================================
setlocal
title cv-research host
cd /d "$RepoRoot"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$startScript" -OpenWhenRunning -Interactive %*
set EXITCODE=%ERRORLEVEL%
if not "%EXITCODE%"=="0" (
  echo.
  echo [!] Launcher exited with code %EXITCODE%. Messages above explain why.
  echo     Tip: run with -DryRun to only check prerequisites.
  pause
)
endlocal
"@

# 明确写成 ASCII（无 BOM）：任何非 ASCII 字节都会在 cmd.exe 里变乱码
[System.IO.File]::WriteAllText($launcherPath, $launcher, [System.Text.Encoding]::ASCII)

Write-Host '── 已安装桌面入口 ─────────────────────────────────' -ForegroundColor Cyan
Write-Host ("  文件      = {0}" -f $launcherPath) -ForegroundColor Green
Write-Host ("  仓库根    = {0}" -f $RepoRoot)
Write-Host ("  启动脚本  = {0}" -f $startScript)

# ── 2. 开始菜单快捷方式（可选）────────────────────────────────────────────
if (-not $NoStartMenu) {
    $programs = [Environment]::GetFolderPath('Programs')
    $lnkPath = Join-Path $programs 'CV-Research 宿主.lnk'
    try {
        $shell = New-Object -ComObject WScript.Shell
        $shortcut = $shell.CreateShortcut($lnkPath)
        $shortcut.TargetPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        $shortcut.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$startScript`" -OpenWhenRunning -Interactive"
        $shortcut.WorkingDirectory = $RepoRoot
        $shortcut.Description = '启动 cv-research 宿主（dsh web）'
        $shortcut.IconLocation = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe,0"
        $shortcut.Save()
        Write-Host '── 已安装开始菜单入口 ─────────────────────────────' -ForegroundColor Cyan
        Write-Host ("  快捷方式  = {0}（开始菜单搜 `"cv`" 即可）" -f $lnkPath) -ForegroundColor Green
    } catch {
        Write-Host ("  ⚠ 开始菜单快捷方式创建失败（不影响桌面入口）：{0}" -f $_.Exception.Message) -ForegroundColor Yellow
    }
}

Write-Host ''
Write-Host '用法：双击桌面上的「启动 CV-Research」' -ForegroundColor White
Write-Host '  · 宿主已在运行 → 直接打开浏览器' -ForegroundColor Gray
Write-Host '  · 宿主没运行   → 注入代理/密钥/skill 根后启动' -ForegroundColor Gray
Write-Host '  · 只想检查环境 → 在该 cmd 上右键编辑，或在 PowerShell 里加 -DryRun' -ForegroundColor Gray
